/**
 * Helpers for the multi-berm SPCC plan model.
 *
 * See: supabase/migrations/20260423000000_create_spcc_plans_table.sql
 */

import { supabase } from '../lib/supabase';
import type { Facility, SPCCPlan } from '../lib/supabase';

export interface FacilityWell {
  /** 1-based index (matches well_name_N / well_api_N columns). */
  index: number;
  /** Display name ("Well 1" fallback if the column is populated but blank). */
  name: string;
  /** API number if available. */
  api: string | null;
}

/**
 * Returns the wells that actually exist on the facility, in index order.
 * Skips the slots whose well_name_N is null/empty.
 */
export function getFacilityWells(facility: Facility): FacilityWell[] {
  const wells: FacilityWell[] = [];
  for (let i = 1; i <= 6; i++) {
    const name = (facility as any)[`well_name_${i}`] as string | null | undefined;
    const api = (facility as any)[`well_api_${i}`] as string | null | undefined;
    if (name != null && String(name).trim() !== '') {
      wells.push({
        index: i,
        name: String(name).trim(),
        api: api && String(api).trim() !== '' ? String(api).trim() : null,
      });
    }
  }
  return wells;
}

/**
 * Union of all well indices covered by any plan in the list.
 */
export function getAllAssignedWellIndices(plans: SPCCPlan[]): Set<number> {
  const out = new Set<number>();
  for (const plan of plans) {
    for (const i of plan.assigned_well_indices || []) out.add(i);
  }
  return out;
}

/**
 * Wells that exist on the facility but aren't assigned to any berm/plan.
 * Only meaningful when there are ≥2 plans — with a single plan, all wells are
 * assumed covered.
 */
export function getUnassignedWells(
  facility: Facility,
  plans: SPCCPlan[]
): FacilityWell[] {
  if (plans.length <= 1) return [];
  const assigned = getAllAssignedWellIndices(plans);
  return getFacilityWells(facility).filter((w) => !assigned.has(w.index));
}

/**
 * Display label for a berm. "Berm 1" or "Berm 1 — North Berm" when labelled.
 */
export function getBermDisplayLabel(plan: Pick<SPCCPlan, 'berm_index' | 'berm_label'>): string {
  const base = `Berm ${plan.berm_index}`;
  const label = plan.berm_label?.trim();
  return label ? `${base} — ${label}` : base;
}

/**
 * Short display label — "Berm 1" (ignores any custom label). For places where
 * space is tight.
 */
export function getBermShortLabel(plan: Pick<SPCCPlan, 'berm_index'>): string {
  return `Berm ${plan.berm_index}`;
}

/**
 * The canonical SPCC plan filename format Israel requires:
 *
 *   {Facility Name} - {Camino Facility ID} - SPCC Plan|SPCC Recert (MM-DD-YY).pdf
 *
 * - kind="plan"    → "SPCC Plan"   (initial plan uploads, replacements that
 *                    aren't recertifications)
 * - kind="renewal" → "SPCC Recert" (PDFs generated by the
 *                    "Create / Regenerate Recertification Plan" workflow)
 *
 * Facility name source: `facility.name` (the user-visible / editable name)
 * with case preserved exactly as typed — no upper/title-casing. The
 * canonical-but-sometimes-uppercased `matched_facility_name` is only used
 * as a fallback when name is missing. Pick the source at the call site
 * via `pickFacilityFilenameName(facility)`.
 *
 * Camino Facility ID: when missing, "NoID" placeholder so the filename
 * still parses cleanly. The user should fill it in on the General tab.
 *
 * Sanitisation: strips characters that break filesystems or Supabase Storage
 * paths (`/ \ : * ? " < > |`). Collapses runs of whitespace into single
 * spaces and trims.
 */
export function buildPlanFilename(opts: {
  facilityName: string;
  caminoFacilityId: string | null | undefined;
  kind: 'plan' | 'renewal';
  /** ISO date or timestamp — only YYYY-MM-DD is read. */
  date: string;
}): string {
  const sanitize = (s: string) =>
    s.replace(/[/\\:*?"<>|]/g, '').replace(/\s+/g, ' ').trim();

  const name = sanitize(opts.facilityName) || 'Unnamed Facility';
  const id = opts.caminoFacilityId
    ? sanitize(opts.caminoFacilityId) || 'NoID'
    : 'NoID';
  const kindLabel = opts.kind === 'renewal' ? 'SPCC Recert' : 'SPCC Plan';
  const m = opts.date.match(/^(\d{4})-(\d{2})-(\d{2})/);
  const dateStr = m ? `${m[2]}-${m[3]}-${m[1].slice(2)}` : '';
  return `${name} - ${id} - ${kindLabel} (${dateStr}).pdf`;
}

/**
 * Picks the "facility name" source for filenames: the user-visible
 * `facility.name` (exact case preserved), with `matched_facility_name`
 * as a fallback only when name is missing.
 *
 * Earlier this preferred `matched_facility_name` because Israel called it
 * "the name from the Facility ID Sheet" — but those import-style canonical
 * names are sometimes uppercased (e.g. "GUTHRIE"), while users want the
 * full descriptive name they typed in the app
 * (e.g. "Guthrie 1MXH, 2WXH, 3MXH"). `facility.name` is that.
 */
export function pickFacilityFilenameName(facility: Pick<Facility, 'name' | 'matched_facility_name'>): string {
  const name = facility.name?.trim();
  if (name) return name;
  return (facility.matched_facility_name || '').trim();
}

/**
 * Storage object path for a plan upload. Berm-aware: plans are grouped
 * under `{facility_id}/berm-{index}/` so it's obvious which PDF belongs
 * to which berm when poking around the Supabase dashboard. The filename
 * portion follows the canonical format from `buildPlanFilename`.
 */
export function buildPlanStoragePath(opts: {
  facilityId: string;
  bermIndex: number;
  facility: Pick<Facility, 'name' | 'matched_facility_name' | 'camino_facility_id'>;
  kind: 'plan' | 'renewal';
  /** ISO date or timestamp; only YYYY-MM-DD is read. */
  date: string;
}): string {
  const filename = buildPlanFilename({
    facilityName: pickFacilityFilenameName(opts.facility),
    caminoFacilityId: opts.facility.camino_facility_id,
    kind: opts.kind,
    date: opts.date,
  });
  return `${opts.facilityId}/berm-${opts.bermIndex}/${filename}`;
}

export interface StandardizeFilenamesProgress {
  total: number;
  processed: number;
  migrated: number;
  skipped: number;
  failed: number;
  /** Human-readable line for the most recent operation (success or failure). */
  lastMessage: string | null;
}

export interface StandardizeFilenamesResult {
  migrated: number;
  skipped: number;
  failed: number;
  messages: string[];
}

/**
 * One-time migration helper: walks every spcc_plans row that has a plan_url
 * and renames the underlying Storage object to the canonical filename
 * Israel specified ("Name - Camino ID - SPCC Plan (MM-DD-YY).pdf").
 *
 * Behavior:
 * - Files already at the canonical path are skipped.
 * - For others: the object is moved (new path) and `spcc_plans.plan_url`
 *   is updated to the new public URL.
 * - "kind" is always 'plan' here — recerts are caught by the recert
 *   workflow itself, which now overwrites in place. Use the Regenerate
 *   button on a per-berm card to apply the canonical "Renewal" filename
 *   to a recertified PDF after this one-time pass.
 * - Date source: pe_stamp_date when present, falling back to
 *   recertified_date, finally today's date so the filename always parses.
 *
 * Idempotent — re-running after a successful pass should report all
 * skipped (already at canonical path).
 */
export async function standardizeAllPlanFilenames(
  onProgress?: (p: StandardizeFilenamesProgress) => void
): Promise<StandardizeFilenamesResult> {
  const messages: string[] = [];

  const { data: plans, error: plansErr } = await supabase
    .from('spcc_plans')
    .select('id, facility_id, berm_index, plan_url, pe_stamp_date, recertified_date');
  if (plansErr) throw plansErr;

  const withUrls = (plans || []).filter((p) => p.plan_url);
  const total = withUrls.length;
  let processed = 0;
  let migrated = 0;
  let skipped = 0;
  let failed = 0;

  const emit = (lastMessage: string | null) => {
    onProgress?.({ total, processed, migrated, skipped, failed, lastMessage });
  };
  emit(null);

  for (const plan of withUrls) {
    let lastMessage: string | null = null;
    try {
      const { data: facility, error: facErr } = await supabase
        .from('facilities')
        .select('id, name, matched_facility_name, camino_facility_id')
        .eq('id', plan.facility_id)
        .single();
      if (facErr || !facility) {
        failed++;
        lastMessage = `Plan ${plan.id}: facility not found — skipping.`;
        messages.push(lastMessage);
        continue;
      }

      const oldPath = (plan.plan_url as string).replace(/^.*\/spcc-plans\//, '');
      const newPath = buildPlanStoragePath({
        facilityId: plan.facility_id,
        bermIndex: plan.berm_index,
        facility,
        kind: 'plan',
        date:
          plan.pe_stamp_date ||
          plan.recertified_date ||
          new Date().toISOString().slice(0, 10),
      });

      if (oldPath === newPath) {
        skipped++;
        lastMessage = `${facility.name}: already canonical, skipped.`;
        messages.push(lastMessage);
        continue;
      }

      const { error: moveErr } = await supabase.storage
        .from('spcc-plans')
        .move(oldPath, newPath);
      if (moveErr) {
        failed++;
        lastMessage = `${facility.name}: move failed — ${moveErr.message}`;
        messages.push(lastMessage);
        continue;
      }

      const {
        data: { publicUrl },
      } = supabase.storage.from('spcc-plans').getPublicUrl(newPath);

      const { error: updErr } = await supabase
        .from('spcc_plans')
        .update({ plan_url: publicUrl })
        .eq('id', plan.id);
      if (updErr) {
        failed++;
        lastMessage = `${facility.name}: DB update failed — ${updErr.message}`;
        messages.push(lastMessage);
        continue;
      }

      migrated++;
      lastMessage = `${facility.name}: → ${newPath.split('/').pop()}`;
      messages.push(lastMessage);
    } catch (err: any) {
      failed++;
      lastMessage = `Plan ${plan.id}: ${err?.message || 'unknown error'}`;
      messages.push(lastMessage);
    } finally {
      processed++;
      emit(lastMessage);
    }
  }

  return { migrated, skipped, failed, messages };
}

/**
 * Given a list of plans, returns the next berm_index to use when adding a new
 * berm. Always one higher than the current max.
 */
export function nextBermIndex(plans: SPCCPlan[]): number {
  if (plans.length === 0) return 1;
  return Math.max(...plans.map((p) => p.berm_index)) + 1;
}

/**
 * Sort plans by berm_index ascending — the UI renders in this order.
 */
export function sortPlansByBermIndex(plans: SPCCPlan[]): SPCCPlan[] {
  return [...plans].sort((a, b) => a.berm_index - b.berm_index);
}
