/*
  # Track when the recertification PDF workflow has actually run

  The "Regenerate Recertification PDF" button on each BermPlanCard was
  showing for berms whose `recertified_date` was set but had never had a
  PDF generated by the in-app workflow — typically because Phase B's
  backfill copied facility-level `recertified_date` values onto every
  berm row.

  This column is set ONLY by the recertification picker workflow on a
  successful generate/regenerate. It's the canonical signal for "we have
  a stamped recertification page in this PDF" and gates the Regenerate
  button accordingly.
*/

ALTER TABLE spcc_plans
  ADD COLUMN IF NOT EXISTS recertification_pdf_generated_at timestamptz;

COMMENT ON COLUMN spcc_plans.recertification_pdf_generated_at IS
  'Set by the in-app recertification PDF workflow on successful generate/regenerate. NULL means no PDF has ever been generated by the workflow (recertified_date alone may be set from backfill or manual data entry).';
