-- LDAR Observation Path
--
-- Stores the editable annotation overlay (walking-path waypoints, numbered
-- stops, and legend bounds) drawn on top of a facility's LDAR site plan PDF.
-- The annotation is generated by an AI vision pass (Gemini, via the
-- ldar-observation-path edge function) and then hand-edited by the user.
--
-- Shape (JSONB):
--   {
--     "stops":      [{ "id": "s1", "number": 1, "x": 0.61, "y": 0.66, "label": "Wellheads (2x)" }, ...],
--     "waypoints":  [{ "x": 0.62, "y": 0.59 }, ...],          // shape-only points along the curve
--     "legend":     { "x": 0.06, "y": 0.85, "w": 0.42, "h": 0.13 },
--     "imageSize":  { "w": 1700, "h": 1200 },                  // px of the source page render; for diagnostics
--     "model":      "gemini-3.1-pro-preview",
--     "generated_at": "2026-05-21T10:30:00Z"
--   }
--
-- All coords are 0..1 normalized to the source PDF page, so the overlay
-- scales with any zoom/resize. NULL = "no path drawn yet". An empty
-- `{ "stops": [], ... }` is also valid (after the user cleared everything).
--
-- ADDITIVE / idempotent. Safe to re-run.

ALTER TABLE facilities
  ADD COLUMN IF NOT EXISTS ldar_observation_path_data JSONB NULL;

COMMENT ON COLUMN facilities.ldar_observation_path_data IS
  'AI-generated + user-edited walking-path overlay for the LDAR site plan PDF. See migration 20260521020000_ldar_observation_path.sql for the JSON shape.';
